POST https://api.notion.com/v1/oauth/token
Content-Type: application/json
Accept: application/json
Authorization: Basic MzRjYTU4MTItNmJlMS00ZTVmLTljNDMtODY1MTIxMGRiZjQyOnNlY3JldF95Q0ZSZTVNelJsc3BDMzY0ZTZma0ROUk9zNm9Jdnlja25qenV2dzFjcXZz

{
    "grant_type": "authorization_code",
    "code": "0306bd03-1a9a-4839-a62d-64cfb6785d38",
    "redirect_uri": "http://localhost:8080"
}

###
GET http://localhost:8080/update/notion


###
GET http://localhost:8080/testEmbedding

###
GET https://api.figma.com/v1/teams/1102794293335508549/projects
Content-Type: application/json


###

POST https://254709ba-813d-4b85-b281-2076c2505c74.us-east4-0.gcp.cloud.qdrant.io/collections/figma_test/points/query
Content-Type: application/json

{
    "query": [0.2, 0.1, 0.9, 0.7] 
}